const GAME_DATA = {
  classes: [
    {
      id: "foresta-1",
      name: "Fauno",
      origin: "Foresta 1",
      zoneId: "foresta-elisir",
      stats: { velocita: 6, vita: 70, forza: 3, intelligenza: 19 },
    },
    {
      id: "foresta-2",
      name: "Mago",
      origin: "Foresta 2",
      zoneId: "foresta-parlante",
      stats: { velocita: 7, vita: 60, forza: 2, intelligenza: 19 },
    },
    {
      id: "deserto-1",
      name: "Ladro",
      origin: "Deserto 1",
      zoneId: "deserto-roccia",
      stats: { velocita: 3, vita: 90, forza: 9, intelligenza: 9 },
    },
    {
      id: "deserto-2",
      name: "Soldato lucertola",
      origin: "Deserto 2",
      zoneId: "deserto-dune",
      stats: { velocita: 8, vita: 60, forza: 4, intelligenza: 9 },
    },
    {
      id: "montagna-1",
      name: "Nano",
      origin: "Montagna 1",
      zoneId: "montagna-miniere",
      stats: { velocita: 7, vita: 60, forza: 5, intelligenza: 9 },
    },
    {
      id: "montagna-2",
      name: "Wandering Trader",
      origin: "Montagna 2",
      zoneId: "montagna-nebbiose",
      stats: { velocita: 2, vita: 90, forza: 10, intelligenza: 9 },
    },
    {
      id: "palude-1",
      name: "Orco",
      origin: "Palude 1",
      zoneId: "palude-mangrovie",
      stats: { velocita: 4, vita: 70, forza: 5, intelligenza: 19 },
    },
    {
      id: "palude-2",
      name: "Scheletro",
      origin: "Palude 2",
      zoneId: "palude-maya",
      stats: { velocita: 5, vita: 60, forza: 4, intelligenza: 19 },
    },
  ],
  zones: [
    {
      id: "deserto-roccia",
      ring: 1,
      biome: "Deserto",
      name: "Deserto di roccia",
      type: "Deserto 1",
      detail: "Zona calda con coperture. Personaggio collegato: Ladro.",
      guardian: "Ophionax",
    },
    {
      id: "deserto-dune",
      ring: 1,
      biome: "Deserto",
      name: "Dune di sabbia",
      type: "Deserto 2",
      detail: "Zona meno calda e senza coperture. Personaggio collegato: Soldato lucertola.",
      guardian: "Ophionax",
    },
    {
      id: "foresta-elisir",
      ring: 1,
      biome: "Foresta",
      name: "Foresta di elisir",
      type: "Foresta 1",
      detail: "Alberi di elisir. Personaggio collegato: Fauno.",
      guardian: "Thyrmocca",
    },
    {
      id: "foresta-parlante",
      ring: 1,
      biome: "Foresta",
      name: "Foresta parlante",
      type: "Foresta 2",
      detail: "Alberi senzienti. Personaggio collegato: Mago.",
      guardian: "Thyrmocca",
    },
    {
      id: "montagna-miniere",
      ring: 1,
      biome: "Montagna",
      name: "Miniere di Bjok Crag",
      type: "Montagna 1",
      detail: "Montagna nera, neve e ghiaccio. Personaggio collegato: Nano.",
      guardian: "Bolgor",
    },
    {
      id: "montagna-nebbiose",
      ring: 1,
      biome: "Montagna",
      name: "Montagne nebbiose",
      type: "Montagna 2",
      detail: "Erba e nebbia. Personaggio collegato: Wandering Trader.",
      guardian: "Bolgor",
    },
    {
      id: "palude-mangrovie",
      ring: 1,
      biome: "Palude",
      name: "Selva di mangrovie",
      type: "Palude 1",
      detail: "Fitta foresta di mangrovie. Personaggio collegato: Orco.",
      guardian: "Glozarr",
    },
    {
      id: "palude-maya",
      ring: 1,
      biome: "Palude",
      name: "Rovine paludose maya",
      type: "Palude 2",
      detail: "Rovine di villaggi maya. Personaggio collegato: Scheletro.",
      guardian: "Glozarr",
    },
    {
      id: "labirinto-minotauro",
      ring: 2,
      biome: "Labirinto",
      name: "Labirinto del Minotauro",
      type: "Dal deserto",
      detail: "Rovine mitiche; uscita verso la sala del Minotauro.",
      guardian: "Minotauro",
    },
    {
      id: "foresta-anfiria",
      ring: 2,
      biome: "Foresta",
      name: "Foresta di Anfiria",
      type: "Dalla foresta",
      detail: "Foresta antichissima; uscita dal Sentiero dei Re.",
      guardian: "Ent antico",
    },
    {
      id: "lago-zero-assoluto",
      ring: 2,
      biome: "Montagna",
      name: "Lago Zero Assoluto",
      type: "Dalla montagna",
      detail: "Temperature bassissime; arco finale protetto dallo Yeti.",
      guardian: "Yeti",
    },
    {
      id: "ziggurat-assurbanipal",
      ring: 2,
      biome: "Palude",
      name: "Ziggurat di Assurbanipal",
      type: "Dalla palude",
      detail: "Cammino degli dei tra siepi, lagune e rovine antiche.",
      guardian: "Wendigo",
    },
    {
      id: "citta-portale",
      ring: 3,
      biome: "Citta",
      name: "Citta e portale",
      type: "Cerchio 3",
      detail: "Rifornimenti, nemici potenti e portale per tornare alla dimensione iniziale.",
      guardian: "Guardiano della dimensione",
    },
  ],
  items: [
    { id: "spada-legno", name: "Spada di legno", type: "Arma", summary: "Cerchio 1; Deserto, Palude" },
    { id: "spada-pietra", name: "Spada di pietra", type: "Arma", summary: "Cerchio 1; Deserto, Montagna" },
    { id: "spada-bronzo", name: "Spada di bronzo", type: "Arma", summary: "Cerchio 1; Foresta, Montagna" },
    { id: "spada-rubino", name: "Spada di rubino", type: "Arma", summary: "Cerchio 1; Foresta, Palude" },
    { id: "lancia-legno", name: "Lancia di legno", type: "Arma", summary: "Cerchio 1; Montagna, Palude" },
    { id: "lancia-bronzo", name: "Lancia di bronzo", type: "Arma", summary: "Cerchio 1; Foresta, Montagna" },
    { id: "lancia-rubino", name: "Lancia di rubino", type: "Arma", summary: "Catalogo armi" },
    { id: "scudo-bronzo", name: "Scudo di bronzo", type: "Arma", summary: "Cerchio 1; Deserto, Foresta" },
    { id: "scudo-rubino", name: "Scudo di rubino", type: "Arma", summary: "Cerchio 1; Montagna" },
    { id: "martello-bronzo", name: "Martello di bronzo", type: "Arma", summary: "Cerchio 1; Foresta, Montagna, Palude" },
    { id: "martello-rubino", name: "Martello di rubino", type: "Arma", summary: "Cerchio 1; Foresta" },
    { id: "pugnale-bronzo", name: "Pugnale di bronzo", type: "Arma", summary: "Cerchio 1; Deserto, Montagna, Palude" },
    { id: "pugnale-legno", name: "Pugnale di legno", type: "Arma", summary: "Cerchio 1; Montagna" },
    { id: "pugnale-pietra", name: "Pugnale di pietra", type: "Arma", summary: "Cerchio 1; Palude" },
    { id: "spada-doppia-pietra", name: "Spada doppia di pietra", type: "Arma", summary: "Cerchio 1; Deserto, Foresta, Palude" },
    { id: "spada-doppia-bronzo", name: "Spada doppia di bronzo", type: "Arma", summary: "Cerchio 1; Montagna, Palude" },
    { id: "ascia-pietra", name: "Ascia di pietra", type: "Arma", summary: "Cerchio 1; Deserto, Montagna" },
    { id: "ascia-bronzo", name: "Ascia di bronzo", type: "Arma", summary: "Cerchio 1; Deserto, Montagna" },
    { id: "ascia-rubino", name: "Ascia di rubino", type: "Arma", summary: "Cerchio 1; Palude" },
    { id: "spada-doppia-smeraldo", name: "Spada doppia di smeraldo", type: "Arma", summary: "Catalogo armi" },
    { id: "ampolla-vita", name: "Ampolla vita", type: "Pozione", summary: "+20 vita; Cerchio 1 Foresta/Palude", apply: { kind: "maxHp", amount: 20 } },
    { id: "ampolla-velocita", name: "Ampolla velocita", type: "Pozione", summary: "+2 velocita; Cerchio 1 Montagna/Palude", apply: { kind: "stat", stat: "velocita", amount: 2 } },
    { id: "ampolla-intelligenza", name: "Ampolla intelligenza", type: "Pozione", summary: "+4 intelligenza; Cerchio 1 Palude/Foresta", apply: { kind: "stat", stat: "intelligenza", amount: 4 } },
    { id: "ampolla-forza", name: "Ampolla forza", type: "Pozione", summary: "+2 forza; Cerchio 1 Deserto/Montagna", apply: { kind: "stat", stat: "forza", amount: 2 } },
    { id: "calice-vita", name: "Calice vita", type: "Pozione", summary: "+35 vita; Cerchio 2 Foresta/Ziggurat", apply: { kind: "maxHp", amount: 35 } },
    { id: "calice-velocita", name: "Calice velocita", type: "Pozione", summary: "+3 velocita; Cerchio 2 Lago/Ziggurat", apply: { kind: "stat", stat: "velocita", amount: 3 } },
    { id: "calice-intelligenza", name: "Calice intelligenza", type: "Pozione", summary: "+5 intelligenza; Cerchio 2 Ziggurat/Foresta", apply: { kind: "stat", stat: "intelligenza", amount: 5 } },
    { id: "calice-forza", name: "Calice forza", type: "Pozione", summary: "+3 forza; Cerchio 2 Labirinto/Lago", apply: { kind: "stat", stat: "forza", amount: 3 } },
    { id: "anfora-vita", name: "Anfora vita", type: "Pozione", summary: "+50 vita; Citta", apply: { kind: "maxHp", amount: 50 } },
    { id: "anfora-velocita", name: "Anfora velocita", type: "Pozione", summary: "+4 velocita; Citta", apply: { kind: "stat", stat: "velocita", amount: 4 } },
    { id: "anfora-intelligenza", name: "Anfora intelligenza", type: "Pozione", summary: "+7 intelligenza; Citta", apply: { kind: "stat", stat: "intelligenza", amount: 7 } },
    { id: "anfora-forza", name: "Anfora forza", type: "Pozione", summary: "+4 forza; Citta", apply: { kind: "stat", stat: "forza", amount: 4 } },
    { id: "cura-grado-1", name: "Pozione cura grado 1", type: "Cura", summary: "Cura 7; Cerchio 1 Montagna/Palude/Foresta", apply: { kind: "heal", amount: 7 } },
    { id: "cura-grado-2", name: "Pozione cura grado 2", type: "Cura", summary: "Cura 15; Cerchio 1-2 Deserto/Montagna", apply: { kind: "heal", amount: 15 } },
    { id: "cura-grado-3", name: "Pozione cura grado 3", type: "Cura", summary: "Cura 25; Cerchio 2 Montagna/Palude/Foresta", apply: { kind: "heal", amount: 25 } },
    { id: "cura-elite", name: "Pozione cura elite", type: "Cura", summary: "Cura 50; Citta", apply: { kind: "heal", amount: 50 } },
    { id: "pozione-invisibilita", name: "Pozione invisibilita", type: "Effetto", summary: "2 turni; movimento nascosto", apply: { kind: "effect", effectId: "invisibilita", turns: 2 } },
    { id: "pozione-fortuna", name: "Pozione fortuna", type: "Effetto", summary: "Guarda 3 carte cassa, tienine 1", apply: { kind: "effect", effectId: "fortuna", turns: 1 } },
    { id: "pozione-teletrasporto", name: "Pozione teletrasporto", type: "Effetto", summary: "Sposta in una casella dello stesso cerchio; non in combattimento", apply: { kind: "effect", effectId: "teletrasporto", turns: 1 } },
  ],
  effects: [
    { id: "invisibilita", name: "Invisibilita", turns: 2, detail: "Movimento non visto dagli altri giocatori." },
    { id: "fortuna", name: "Fortuna", turns: 1, detail: "Quando apri una cassa guarda 3 carte, prendine 1 e rimetti le altre in cima." },
    { id: "teletrasporto", name: "Teletrasporto", turns: 1, detail: "Spostamento manuale nello stesso cerchio; non valido in combattimento." },
    { id: "combattimento", name: "In combattimento", turns: 0, detail: "Stato manuale per bloccare movimento o segnare scontri." },
    { id: "ferito", name: "Ferito", turns: 0, detail: "Segnalino libero per playtest." },
  ],
  quickRules: [
    {
      title: "Movimento",
      body: "Lancia un d10. Il risultato indica le caselle percorribili; nella mappa v1 lo spostamento resta manuale.",
    },
    {
      title: "Nuoto",
      body: "Il movimento in acqua vale meta' del d10, con valore massimo 5.",
    },
    {
      title: "Fuga",
      body: "Per scappare dal combattimento serve il complementare della velocita': velocita' + target = 10.",
    },
    {
      title: "Vincoli",
      body: "Non e' consentito arrampicarsi, scavalcare, saltare ostacoli o saltare trappole.",
    },
    {
      title: "Combattimento",
      body: "Danni e risoluzione non sono definiti nel documento: registrarli nel log come decisioni di playtest.",
    },
  ],
};
